# Generated by Django 6.0.6 on 2026-07-02 15:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('img_usuario', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('estado', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grado', models.CharField(choices=[('Preescolar', 'Preescolar'), ('1', '1°'), ('2', '2°'), ('3', '3°'), ('4', '4°'), ('5', '5°'), ('6', '6°'), ('7', '7°'), ('8', '8°'), ('9', '9°'), ('10', '10°'), ('11', '11°')], max_length=20)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('capacidad', models.IntegerField()),
                ('fechainicio', models.DateTimeField(auto_now_add=True)),
                ('fechafin', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'Curso',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'evento',
            },
        ),
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='tipoelemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'tipoelemento',
                'verbose_name_plural': 'tipoelementos',
                'db_table': 'tipoelemento',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'unidadmedida',
            },
        ),
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telefono', models.TextField(blank=True, max_length=10, null=True, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Acudiente',
                'verbose_name_plural': 'Acudientes',
                'db_table': 'Acudiente',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cargo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='docente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('especialidad', models.TextField()),
            ],
            options={
                'verbose_name': 'docente',
                'verbose_name_plural': 'docentes',
                'db_table': 'docente',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('estadoMatricula', models.CharField(choices=[('Matriculado', 'Matriculado'), ('No Matriculado', 'No Matriculado'), ('Retirado', 'Retirado'), ('Graduado', 'Graduado'), ('Sancionado', 'Sancionado')], default='Matriculado', max_length=20)),
                ('fechaIngreso', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Ingreso')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('qr', models.ImageField(blank=True, upload_to='usuarios/')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'Estudiante',
            },
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('stockActual', models.IntegerField()),
                ('stockMinimo', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('categoriaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
                ('marcaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marca')),
                ('tipoElementoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoelemento')),
                ('unidadMedidaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unidadmedida')),
            ],
            options={
                'verbose_name': 'Elemento',
                'verbose_name_plural': 'Elementos',
                'db_table': 'elemento',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=50)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('cantidad', models.IntegerField()),
                ('motivo', models.TextField()),
                ('cursoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso')),
                ('elementoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.elemento')),
                ('usuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimiento',
                'db_table': 'movimiento',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('no_leida', 'No Leída'), ('leida', 'Leída')], default='no_leida', max_length=20)),
                ('tipo', models.CharField(choices=[('aviso', 'Aviso'), ('actualizacion', 'Actualización'), ('urgente', 'Urgente')], default='aviso', max_length=50)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.evento')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificacion',
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='creador_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.administrador'),
        ),
        migrations.AddField(
            model_name='curso',
            name='docenteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.docente'),
        ),
        migrations.CreateModel(
            name='Estudianteacudiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acudienteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.acudiente')),
                ('estudianteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estudiante')),
            ],
            options={
                'verbose_name': 'Estudianteacudiente',
                'verbose_name_plural': 'Estudianteacudientes',
                'db_table': 'Estudianteacudiente',
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='cursoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now=True)),
                ('horaentrada', models.TimeField()),
                ('horasalida', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('A tiempo', 'A tiempo'), ('Tarde', 'Tarde'), ('Inasistencia', 'Inasistencia')], max_length=20)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('estudianteid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estudiante')),
            ],
            options={
                'verbose_name': 'asistencia',
                'verbose_name_plural': 'asistencias',
                'db_table': 'asistencia',
            },
        ),
    ]
